In [1]:
import pandas as pd
import numpy as np


In [2]:
data=pd.read_csv("haberman.csv")

In [8]:
data.head(10)

age  year  nodes  status
0   30    64      1       1
1   30    62      3       1
2   30    65      0       1
3   31    59      2       1
4   31    65      4       1
5   33    58     10       1
6   33    60      0       1
7   34    59      0       2
8   34    66      9       2
9   34    58     30       1

*top 10  rows

In [7]:
data.tail(10)

age  year  nodes  status
296   72    67      3       1
297   73    62      0       1
298   73    68      0       1
299   74    65      3       2
300   74    63      0       1
301   75    62      1       1
302   76    67      0       1
303   77    65      3       1
304   78    65      1       2
305   83    58      2       2

*last 10 rows

In [12]:
data["age"].unique()

array([30, 31, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
       65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 83],
      dtype=int64)

In [13]:
data["year"].unique()

array([64, 62, 65, 59, 58, 60, 66, 61, 67, 63, 69, 68], dtype=int64)

In [14]:
data["nodes"].unique()

array([ 1,  3,  0,  2,  4, 10,  9, 30,  7, 13,  6, 15, 21, 11,  5, 23,  8,
       20, 52, 14, 19, 16, 12, 24, 46, 18, 22, 35, 17, 25, 28],
      dtype=int64)

In [15]:
data["status"].unique()

array([1, 2], dtype=int64)

In [4]:
import sweetviz

# Analyzing the single variable

In [18]:
quick_EDA = sweetviz.analyze(data)


                                   |                         | [  0%]   00:00  -> (? left)
Summarizing dataframe:             |                         | [  0%]   00:00  -> (? left)
:age:                              |████████▍            | [ 40%]   00:00  -> (00:00 left)
:age:                              |████████████▌        | [ 60%]   00:01  -> (00:00 left)
:year:                             |████████████▌        | [ 60%]   00:01  -> (00:00 left)
:year:                             |████████████████▊    | [ 80%]   00:01  -> (00:00 left)
:nodes:                            |████████████████▊    | [ 80%]   00:01  -> (00:00 left)
:nodes:                            |█████████████████████| [100%]   00:02  -> (00:00 left)
:status:                           |█████████████████████| [100%]   00:02  -> (00:00 left)
:status:                           |                     | [  0%]   00:03  -> (00:00 left)
:FEATURES DONE:                    |                     | [  0%]   00:03  -> (00:00 left

Creating Associations graph... DONE!


In [19]:
quick_EDA.show_html('Report.html')

# observation :